port: /dev/ttyUSB0
baud_rate: 921600
async_port: 2
async_rate_divisor: 1
is_triggered: false
sync_in_skip_factor: 0
is_triggering: true
sync_out_skip_factor: 39
sync_out_pulse_width: 1.0e+9
get_uncomp_measurements: true
frame_id: imu_link