name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: noetic
        
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y libspdlog-dev
        
    - name: Create catkin workspace
      run: |
        source /opt/ros/noetic/setup.bash
        mkdir -p catkin_ws/src
        ln -s $GITHUB_WORKSPACE catkin_ws/src/vectornav
        
    - name: Install ROS dependencies
      run: |
        source /opt/ros/noetic/setup.bash
        cd catkin_ws
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
        
    - name: Build package
      run: |
        source /opt/ros/noetic/setup.bash
        cd catkin_ws
        catkin_make -DCMAKE_BUILD_TYPE=Release

    - name: Run tests
      run: |
        source /opt/ros/noetic/setup.bash
        cd catkin_ws
        source devel/setup.bash
        catkin_make run_tests
