name: Build ROS Package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_ros2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: [humble, jazzy]
    container: osrf/ros:${{ matrix.ros_distro }}-desktop-full
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: src/${{ github.event.repository.name }}

    - name: Install ROS dependencies (rosdep)
      run: |
        apt-get update
        # Initialize rosdep if not already done
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          rosdep init
        fi
        # Update rosdep as regular user (non-sudo)
        rosdep update --include-eol-distros
        rosdep install --from-paths src --ignore-src -y --rosdistro ${{ matrix.ros_distro }}
      shell: bash

    - name: Build ROS package with colcon
      run: |
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        colcon build --symlink-install
      shell: bash

  build_ros1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: [noetic]
    container: osrf/ros:${{ matrix.ros_distro }}-desktop-full
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: src/${{ github.event.repository.name }}

    - name: Install ROS dependencies (rosdep)
      run: |
        apt-get update
        # Initialize rosdep if not already done
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          rosdep init
        fi
        # Update rosdep as regular user (non-sudo)
        rosdep update --include-eol-distros
        rosdep install --from-paths src --ignore-src -y --rosdistro ${{ matrix.ros_distro }}
      shell: bash

    - name: Build ROS package with catkin_make
      run: |
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        catkin_make -DCMAKE_BUILD_TYPE=Release
      shell: bash
