# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Formatting (pre-commit)

on:
  workflow_dispatch:
  push:

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - uses: pre-commit/action@v3.0.1
      id: precommit
    - name: Upload pre-commit changes
      if: failure() && steps.precommit.outcome == 'failure'
      uses: rhaschke/upload-git-patch-action@main
      with:
        name: pre-commit
